export const FREE_TIER_LIMITS = {
  NEON_FREE_COMPUTE_HOURS: 191.9,
  GEMINI_FREE_REQUESTS_DAY_FLASH: 500,
  GEMINI_FREE_REQUESTS_DAY_PRO: 25,
  GEMINI_AUTH_REQUESTS_DAY: 1000,
  GROQ_FREE_RPM: 30,
  RESEND_FREE_EMAILS_DAY: 100,
  BREVO_FREE_EMAILS_DAY: 300,
  SENTRY_FREE_ERRORS_MONTH: 5000,
  GITHUB_ACTIONS_FREE_MINUTES_MONTH: 2000,
  SUPABASE_STORAGE_FREE_GB: 1,
  ORACLE_OBJECT_STORAGE_FREE_GB: 20,
  CLOUDFLARE_R2_FREE_GB: 10,
  CLOUDFLARE_PAGES_FREE_BUILDS_MONTH: 500,
  VERCEL_FREE_BANDWIDTH_GB_MONTH: 100
} as const;
