export interface Template {
  id: string;
  name: string;
  slug: string;
  description: string;
  longDescription: string | null;
  category: string;
  tags: string[];
  previewUrl: string | null;
  thumbnailUrl: string;
  screenshots: Record<string, any>[];
  fileTree: Record<string, any>;
  databaseSchema: Record<string, any> | null;
  features: Record<string, any>[];
  isOfficial: boolean;
  isFeatured: boolean;
  authorId: string | null;
  priceCents: number;
  installCount: number;
  ratingAvg: number;
  ratingCount: number;
  createdAt: Date;
  updatedAt: Date;
}

export type TestSuiteType = 'unit' | 'integration' | 'e2e' | 'visual' | 'performance' | 'accessibility';
export type TestRunStatus = 'passed' | 'failed' | 'skipped' | 'error';

export interface TestSuite {
  id: string;
  projectId: string;
  name: string;
  description: string | null;
  type: TestSuiteType | null;
  testCode: string;
  testFilePath: string;
  isAutoGenerated: boolean;
  isActive: boolean;
  lastRunStatus: TestRunStatus | null;
  lastRunAt: Date | null;
  lastRunDurationMs: number | null;
  passCount: number;
  failCount: number;
  coveragePercent: number | null;
  createdAt: Date;
  updatedAt: Date;
}
