import { pgTable, uuid, varchar, text, boolean, integer, decimal, timestamp } from 'drizzle-orm/pg-core';
import { projects } from './projects';

export const testSuites = pgTable('test_suites', {
  id: uuid('id').primaryKey().defaultRandom(),
  projectId: uuid('project_id').references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  type: varchar('type', { length: 20 }), // CHECK IN ('unit','integration','e2e','visual','performance','accessibility')
  testCode: text('test_code').notNull(),
  testFilePath: text('test_file_path').notNull(),
  isAutoGenerated: boolean('is_auto_generated').default(true),
  isActive: boolean('is_active').default(true),
  lastRunStatus: varchar('last_run_status', { length: 20 }), // CHECK IN ('passed','failed','skipped','error')
  lastRunAt: timestamp('last_run_at', { withTimezone: true }),
  lastRunDurationMs: integer('last_run_duration_ms'),
  passCount: integer('pass_count').default(0),
  failCount: integer('fail_count').default(0),
  coveragePercent: decimal('coverage_percent', { precision: 5, scale: 2 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});
